name: C++ CI

on:
  push:
      branches: [develop, main]
  pull_request:
      branches: [develop, main]

jobs:
  Build-and-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout Source
          uses: actions/checkout@v3
        
        - name:  Install dependencies (Linux)
          if: runner.os != 'Windows'
          run: |
            sudo apt-get update || true
            sudo apt-get install -y cmake g++ || true
            sudo apt-get install -y gcovr || true 

        - name: Install dependencies (Window)
          if: runner.os == 'Windows'
          run: |
            choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=System"' -y || true
            pip install gcovr || true
        
        - name: Configure
          run: cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release

        - name: Build
          run: cmake --build build --config Release

        - name: Run tests
          run: ctest -C Release --test-dir build --output-on-failure
        
        - name: Generate coverage report
          run: gcovr -r . --xml -o coverage.xml

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
            files: coverage.xml
            token: ${{ secrets.CODECOV_TOKEN }}